language: ruby
services: mongodb
gemfile:
  - gemfiles/mongoid2.gemfile
  - gemfiles/mongoid3.gemfile
rvm:
  - 1.9.2
  - 1.9.3
  - rbx-19mode
  - jruby-19mode
matrix:
  exclude:
    - rvm: 1.9.2
      gemfile: gemfiles/mongoid3.gemfile
    - rvm: rbx-19mode
      gemfile: gemfiles/mongoid2.gemfile